version: '3'

  # vueプロジェクト
services:
  app:
    build: .
    container_name: vue-project
    ports:
      - '8080:8080'
    volumes:
      - C:\Users\kojimasota\tsugitasu:/src
    stdin_open: true
    tty: true