version: '3'

  # vueプロジェクト
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue-project
    ports:
      - '8080:8080'
    volumes:
      - ./:/src
    stdin_open: true
    tty: true